### ISSUE TITLE
get_block_template rpcf返回错误是什么原因，按照例子写的

### ISSUE THREAD

**Issue by rocqina** [nervosnetwork/ckb#1834]
curl -X POST http://localhost:8114 -d '{"id": 1,”jsonrpc": "2.0","method": "get_block_template","params": [null,null,null]}' -H 'content-type:application/json' 

{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}

**Comment by keroro520** [comment]
`”jsonrpc"` => `"jsonrpc"`

**Comment by rocqina** [comment]
curl -X POST 'http://localhost:8114' -d '{"id": 1,jsonrpc": "2.0","method": "get_block_template","params": [null,null,null]}' -H 'content-type:application/json' 
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
还是报错

用代码里的例子也报错
 curl -d '{"id": 2, "jsonrpc": "2.0", "method":"get_block_template","params": ["0x1b1c832d02fdb4339f9868c8a8636c3d9dd10bd53ac7ce99595825bd6beeffb3", 1000, 1000]}' -H 'content-type:application/json' 'localhost:8114' 
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":2}

**Comment by rocqina** [comment]
改了还是报错
curl -X POST http://localhost:8114  -d '{"id": 1,"jsonrpc": "2.0","method": "get_block_template","params": [null,null,null]}' -H 'content-type:application/json' 
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
用代码里的例子还报错
 curl -d '{"id": 2, "jsonrpc": "2.0", "method":"get_block_template","params": ["0x1b1c832d02fdb4339f9868c8a8636c3d9dd10bd53ac7ce99595825bd6beeffb3", 1000, 1000]}' -H 'content-type:application/json' 'localhost:8114' 
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":2}

**Comment by yangby-cryptape** [comment]
First, could u use code blocks, please.

**Comment by rocqina** [comment]
明白了，多谢，测试网是默认加了--ba-arg ；主网需要手动加一下才能工作

**Comment by panchengj** [comment]
我遇到了相同的问题，
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":2}
我起的是测试链，0.26.0版本，rpc调用get_block_hash也要设置--ba-arg吗？

**Comment by yangby-cryptape** [comment]
> 我遇到了相同的问题，
> {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":2}
> 我起的是测试链，0.26.0版本，rpc调用get_live_cells_by_lock_hash也要设置--ba-arg吗？

[Indexer] module is disabled in default. Since it's not an essential part for a chain, it's just an extra function. It requires additional storage.
[get_live_cells_by_lock_hash] is in the [Indexer] module.

https://github.com/nervosnetwork/ckb/blob/a730dfed8ba25b99150fc1f3be9afe62fe09f9df/resource/ckb.toml#L94-L95

[Indexer]: https://github.com/nervosnetwork/ckb/tree/a730dfed8ba25b99150fc1f3be9afe62fe09f9df/rpc#indexer
[get_live_cells_by_lock_hash]: https://github.com/nervosnetwork/ckb/tree/a730dfed8ba25b99150fc1f3be9afe62fe09f9df/rpc#get_live_cells_by_lock_hash
