### ISSUE TITLE
What is the amount of MAX_BLOCK_CYCLES on testnet ? 

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/ckb#2037]
Recently I develop a lock script and it cost about  `0.8 billion`  cycles. According to [code](https://github.com/nervosnetwork/ckb/blob/22829ae85db1643480bd810150f9619250aac92e/spec/src/consensus.rs#L69)   `MAX_BLOCK_CYCLES==3.5 billion` , However when trying to unlock script I get `ExceededMaximumCycles` error.   
So what is exactly the amount of MAX_BLOCK_CYCLES on testnet ?

**Comment by jjyr** [comment]
There are two limitations of cycles in CKB.

1. `MAX_BLOCK_CYCLES`, the consensus layer limitation on the block level.
2. `max_tx_verify_cycles`, the implementation layer limitation on the tx level. https://github.com/nervosnetwork/ckb/blob/develop/resource/ckb.toml#L111

The reason for the tx level limitation is to prevent attackers sent large cycles tx to occupied the CPU of a node. The maintainer of a CKB node can adjust this limitation and send a tx, but other nodes may not relay the tx due to their limitation configuration.

If you are using the dev network, you can change this limitation to send the tx.

**Comment by timfaner** [comment]
Thanks

**Comment by doitian** [comment]
I'm working on improving the ckb errors to avoid such confusions in the future.
