### ISSUE TITLE
rc2 for ckb2021

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#2820]
* [x] @quake Rebase #2817
* [x] @quake rpc `send_transaction` https://github.com/nervosnetwork/ckb/pull/2821
    * [x] `outputs_validator` defaults to `WellKnownScriptsOnly`
    * [x] Add acp / sUDT to the allow list.
    * [x] Support adding more allow list rules via config file.
* [x] @yangby-cryptape Revert `edition` (DUE 2021-07-12) #2822
* [x] @yangby-cryptape Deprecated warning (DUE 2021-07-13) #2822
* [x] #2830
* [x] #2834
* [x] Release rc2 (waiting for https://github.com/nervosnetwork/ckb/actions/runs/1035994213)

**Comment by yangby-cryptape** [comment]
I think we should merge RFCs as many as possible before RC.
Then we fix the links which can be found with `grep -r 'TODO ckb2021'`, and also some comments and identifications.

Otherwise, when users find a feature, they can't find the related RFC.

If there's not enough time, maybe we should let all links point to related pull requests, in order to avoid user's confusions.

**Comment by doitian** [comment]
I'll submit placeholders for those RFCs and link them to the reviewing PRs.
