### ISSUE TITLE
Fix the bug that rc1 testnet/mainnet spec hashes does not match the original values.

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#2834]
* version: v0.100.0-rc1
* platforms: all
* reporter:  @jiangxianliang007 

### Error

```
Jul 15 19:13:57 lina-beijing systemd[1]: Started CKB mainnet node-8114. Jul 15 19:13:57 lina-beijing ckb[379]: WARN: the option "store" in configuration files is deprecated since v0.100.0. Jul 15 19:13:57 lina-beijing ckb[379]: WARN: the option "tx_pool" in configuration files is deprecated since v0.100.0. Jul 15 19:13:58 lina-beijing ckb[379]: chain_spec_hash mismatch Config(Byte32(0xc1d2eae53dbb7bedb2ecbb39b1663952226c1a2b147158ce85b1d5780a63bc96)) storage(Byte32(0x3fe86931c2cf5dfa6d7b9447561b5e547937fe4699787bb7ae906218b3f1e6c5)), pass command line argument --skip-spec-check if you are sure that the two different Jul 15 19:13:58 lina-beijing systemd[1]: ckb-node-8114.service: Main process exited, code=exited, status=65/n/a Jul 15 19:13:58 lina-beijing systemd[1]: ckb-node-8114.service: Failed with result 'exit-code'.
```

### Diff

```diff
diff --git a/docs/hashes.toml b/docs/hashes.toml
index 2961520da..aeffe1d54 100644
--- a/docs/hashes.toml
+++ b/docs/hashes.toml
@@ -2,7 +2,7 @@
 
 # Spec: ckb
 [ckb]
-spec_hash = "0x3fe86931c2cf5dfa6d7b9447561b5e547937fe4699787bb7ae906218b3f1e6c5"
+spec_hash = "0xc1d2eae53dbb7bedb2ecbb39b1663952226c1a2b147158ce85b1d5780a63bc96"
 genesis = "0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5"
 cellbase = "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c"
 
@@ -46,7 +46,7 @@ index = 1
 
 # Spec: ckb_testnet
 [ckb_testnet]
-spec_hash = "0xdde420d56c10a06749e79701b152ed1f532f4bdf0696b5896dfd97fbc821e231"
+spec_hash = "0xe0e6adeaadc8d93ea7e3103722fb9344a19a97971f694b090260e76abb4d1c2d"
 genesis = "0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606"
 cellbase = "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f"
 
@@ -90,7 +90,7 @@ index = 1
 
 # Spec: ckb_staging
 [ckb_staging]
-spec_hash = "0x2d96bd61335be33418befa47f1c5ead53a0546b57a6d79719f0f999fa954dde4"
+spec_hash = "0x7ce187802e11bbdd074546f882d2608574ac20869baafcc1059a77d871e82733"
 genesis = "0xbc081e6b2e31149c1dc39007f161ed0a0b63d5d30b3b771acc6a3b622133fcc0"
 cellbase = "0x7295631c414e50a8d9bb73d9845231ac212d10404045c96de7f149ec874ac6b7"
 
@@ -134,7 +134,7 @@ index = 1
 
 # Spec: ckb_dev
 [ckb_dev]
-spec_hash = "0xa8d7ab92196638cd091d49aa76849f6f102d8082eb374f089477d9c50a4bd2f1"
+spec_hash = "0x360b413b576acc041b778da1a030cfc98fd5d934e2b12ab750aeee1e4ea21017"
 genesis = "0x823b2ff5785b12da8b1363cac9a5cbe566d8b715a4311441b119c39a0367488c"
 cellbase = "0xa563884b3686078ec7e7677a5f86449b15cf2693f3c1241766c6996f206cc541"
```

**Comment by yangby-cryptape** [comment]
### Summary of the Reason

The order of fields in `Script` was changed, so the serialized data was changed, then the hash of spec data was changed.

<details><summary>See the differences.</summary>

- In CKB v0.43.0, `Script` is:

  https://github.com/nervosnetwork/ckb/blob/bbbe5a58f7024f1157fba75f26ab4e2fdfee1e38/util/jsonrpc-types/src/blockchain.rs#L75-L82

- In CKB 0.100.0-rc1, `Script` is

  https://github.com/nervosnetwork/ckb/blob/c472ca3a924152c1a82adb0810ba5afa09548c79/util/jsonrpc-types/src/blockchain.rs#L80-L87

</details>

### Effect Scope

Only 0.100.0-rc1.

### Details about How it Happened

In the next hardfork, CKB 2021, a new version of CKB VM will be introduced, so we have to change the `hash_type` in `Script`.

- In my first solution, the spec hash wasn't changed.

  <details><summary>I just added an optional field <code>vm_version</code> and skipped serialization when its value was 0.</summary>

  https://github.com/nervosnetwork/ckb/blob/e4dac8a043e9fd240c0afc90f594b6413e97bca0/util/jsonrpc-types/src/blockchain.rs#L20-L29

  </details>

- Then, according to the review suggestions, I changed the `hash_type` from `String` to `Object`.

  <details><summary>In this solution, the spec hash was changed since the serialized data was changed.</summary>

  https://github.com/nervosnetwork/ckb/blob/40b449792f17acd23f910233f502991b6843da16/util/jsonrpc-types/src/blockchain.rs#L27-L35

  </details>

  <details><summary>So I introduced a new filed <code>edition</code> to keep the compatibility.</summary>

  https://github.com/nervosnetwork/ckb/blob/40b449792f17acd23f910233f502991b6843da16/spec/src/lib.rs#L451-L460

  </details>

  <details><summary>Worse still, we had to face to an already known bug.</summary>

  https://github.com/nervosnetwork/ckb/blob/40b449792f17acd23f910233f502991b6843da16/spec/src/lib.rs#L9-L11

  </details>

  <details><summary>I had no choice, except to change the order of fields.</summary>

  https://github.com/nervosnetwork/ckb/blob/40b449792f17acd23f910233f502991b6843da16/util/jsonrpc-types/src/blockchain.rs#L157-L164

  </details>

- Things are volatile. Almost the last days before we released the rc1, new opinion said the `hash_type` should be an enumeration type as same as before.

  <details><summary>Then I changed it back to an enumeration type.</summary>

  https://github.com/nervosnetwork/ckb/blob/4aadeb90f552532cf93834f954e0c259b2a2ce6b/util/jsonrpc-types/src/blockchain.rs#L20-L27

  </details>

  <details><summary>After that, I reverted the design of `edition` according to the result of a new discussion, and used the new compatibility policy for configuration files to instead of it.</summary>

  https://github.com/nervosnetwork/ckb/blob/8d1301d074e19a5dee8974d575e81d70adde414f/spec/src/lib.rs#L452-L461

  </details>

  The spec should be changed back to the original value since we decided to revert a compatible design, but I didn't recall this incident.

  So, bug was introduced.
