### ISSUE TITLE
Problems with deploying ckb with docker

### ISSUE THREAD

**Issue by driftluo** [nervosnetwork/ckb#3667]
In Linux environments, the reuse port is enabled by default to allow more nodes to be discovered within the network more easily and to make the network more robust. However, when ckb is started inside docker, the port reuse will be converted to a random port by docker.

We need to do two things.
- Reproduce and troubleshoot the cause of the problem
- Provide a wiki to inform users of the recommended way to use docker

@eval-exec

**Comment by eval-exec** [comment]
# How to Reproduce 

1. start a ckb node on host `A` with `reuse_port_on_linux = true` by executable binary file.
2. start a ckb node on host `B` with `reuse_port_on_linux = true` by docker container: `docker run -p 8115:8115 -p 8114:8114 -d -v $(realpath ckb0-data):/var/lib/ckb  nervos/ckb:v0.104.1 run`
3. stop the ckb container on host `B`, and start ckb node by executable binary file
4. repeat step 2 and step 3, view ckb's log on host `A`(`data/logs/run.log`) , then we can see the outgoing port from host `B` is a random port instead of `8115`

# How to avoid this problem

This problem only occurs when you start the ckb node by docker container，so we **recommand that start ckb by the executable binary file**.
If you insist on using docker，use host network mode for ckb container: `docker run --network host`

# Useful links
[Docker host networking mode tutorial](https://docs.docker.com/network/network-tutorial-host/)

**Comment by driftluo** [comment]
https://github.com/nervosnetwork/ckb/wiki/Deployment-of-ckb
