### ISSUE TITLE
Design the PoC of CKB Open Transaction for Atomic Swap

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3679]
In Atomic Swap scenarios, users publish assets swapping proposals as open transactions. The matching engine commits CKB transactions by combining the matched proposals.

**Comment by TheWaWaR** [comment]
## Basic design
### Actions
* Submit an order
* Cancel an order
* Match Engine match orders generate a CKB transaction and send it

### The Order
* Is a partial signed open transaction, use one input to with cancel the order
* Exchange
  - UDT <==> UDT
  - CKB <==> UDT

### Limits from CKB
* No `until` since type, so user need to cancel the open transaction by sending a CKB transaction to use the cell
