### ISSUE TITLE
Design the PoC of CKB Open Transaction for End-to-end Payment

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3680]
In the end-to-end payment transaction, the client receives the payee information from the merchant directly. The client creates open transactions and the merchant will collect these open transactions by committing the final CKB transactions.

The solution should cover these issues:

- Hot cell issue: transactions are conflict because of using the same input cell. 
- 61 CKB issue: the client does not need to provide the extra CKB capacity to create the cell for the merchant.

**Comment by EthanYuan** [comment]
# Another solution in the End-to-end Payment scenario

## Back to the original question

Let's go back to the original question: "the 61 CKB problem", or “how to pay for less than 61 CKB”.

In the case of one-to-one transfers, ACP is an excellent solution. But it also brings new problems: in many-to-one and concurrent payment scenarios, "acp cell competition" occurs.

Open Transaction is seen as the new solution. What needs to be clarified is whether it is a solution to "the 61 CKB problem" or a solution to "acp cell competition". If Open transaction can directly solve the original problem "the 61 CKB problem", does it still need to solve the competition problem caused by acp cell?

Maybe not needed.

## The acp cell competition problem is difficult to solve

The essence of the acp cell competition problem is: in the context of the UTXO model, the payee ACP cell needs to appear in the input of the transaction. 

In other words, it means that multiple payers cannot coordinately use the payee's ACP cell.

If Open Transaction wants to solve the problem of acp cell competition, then a natural idea is: let Open Transaction have a god's vision.

But even CKB node's transaction pool can't do it, because of decentralization. Competition is always possible as long as the payee's acp cell is used.

## May not need a god vision, just Bob's vision

**Just as the payer can completely schedule its own cells, the payee's cells can only be managed by himself.** It seems that the vision of the payee is enough. Here are some examples to illustrate.

### case 1:  Alice initiates the open tx

Alice wants to transfer 10 CKB to bob, and is only willing to pay 1 CKB as a fee:

```
input: 
	alice's live cell with 100 ckb
	
output: 
	bob's new cell with 61 ckb (min capacity)
	alice's new cell with 89 ckb
```

Alice signs the input and output, and sends the Open Transaction to a service that Bob delegates. The service notifies Bob, who then completes the final transaction.

```
input: 
	alice's live cell with 100 ckb
	
	bob's live cell with 161 ckb
output: 
	bob's new cell with 61 ckb
	alice's new cell with 89 ckb
	
	bob's new cell with 110 ckb
```

Bob can collect multiple such payment requests open txs and combine them to produce a transaction.

### case 2: bob can also initiate open tx
  
As the payee, bob generates a 10 CKB receipt open tx, which is a bit like the   
receipt code in Alipay or WeChat

```
input:
	bob's live cell with 100 ckb
	
output:
	bob's new cell with 110 ckb
```

Bob signs inputs and outputs and directly give alice the Open Tx when alice requests payment. 

Alice can complete and sign the transaction later:

```
input:
	bob's live cell with 100 ckb
	
	alice's live cell with 100 ckb
	
output:
	bob's new cell with 110 ckb
	
	alice's new cell with 89 ckb
```

The input in open tx prepared by bob for each payer is different.

## New problems brought by the open tx above

Open Transaction based on the above solution is simple, but will bring an obvious problem, that is, the interaction of the payee is required.

The ACP solution does this so well that we take it for granted that the payee should not be involved.

But perhaps this problem is easier to solve than the acp cell competition problem. 

For example：

- as the payee, when Bob's wallet receives the open transaction payment notification, it can automatically complete, sign and send it to the CKB chain, so that Bob himself does not need to interact.  
-  or if there is a bank that operates cryptocurrencies, Bob's deposit account can be automatically signed

The basis of automatic signature is the same principle as ACP: as long as there are more outputs.

## Summarize

- The solution above doesn't mind the payee signing, automatic or non-automatic.
- No need to use ACP in Open Tx, avoiding ACP cell competition and being replaced by others.

Whether this method is still applicable in other scenarios needs further discussion
