### ISSUE TITLE
Fix and simplify timestamp-related tests

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/ckb#3729]
Now ckb is using [faketime](https://github.com/nervosnetwork/faketime) to mock time and test for timestamps, faketime is slightly complicated and does not work correctly in some cases, for example, if you specify `--test-threads=1`, timestamp related tests will fail, so we need a new solution to fix these tests, the simplest way should be thread_local or global variable, combined with https://github.com/palfrey/serial_test/.

**Comment by eval-exec** [comment]
I think the thread_local variable in: https://github.com/nervosnetwork/faketime/blob/1ead0aba139f0893d04aa95c35e0179c3b4482c7/src/faketime.rs#L109-L115

should be reset at the very beginning of every unit test function.

**Comment by eval-exec** [comment]
An idea to fix these tests:

https://gist.github.com/eval-exec/177bffa02bdb0302e1d59c94266508d9

**Comment by eval-exec** [comment]
Using serial_test to organize unit tests is a bit cumbersome, because it must add `#[serial]` or `#[parallel]` attributes to all unit tests,

Consider using [nextest-rs/nextest](https://github.com/nextest-rs/nextest), it will run unit tests on different **processes**, providing process-level isolation granularity.
