### ISSUE TITLE
ckb-miner cannot work properly

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/ckb#4032]
## Bug Report

After sending 1 million CKB transactions, start the ckb-miner program. However, after packaging 1,500 transactions in the first block, ckb-miner only continues to package cellbase transactions. There are still 1 million transactions waiting to be included in the chain in the transaction pool.
#### ckb-miner.toml
```
[miner.client]
rpc_url = "http://127.0.0.1:8114/"
block_on_submit = true

# block template polling interval in milliseconds
poll_interval = 100

# enable listen notify mode
#listen = "127.0.0.1:8888"

[[miner.workers]]
worker_type = "Dummy"
delay_type = "Constant"
value = 1000
```
After modifying the configuration, ckb-miner is able to package 1,500 transactions every 4 blocks.
####  ckb-miner.toml
```
[miner.client]
rpc_url = "http://127.0.0.1:8114/"
block_on_submit = true

# block template polling interval in milliseconds
poll_interval = 1000

# enable listen notify mode
# listen = "127.0.0.1:8888"

[[miner.workers]]
worker_type = "Dummy"
delay_type = "Constant"
value = 5000
```

### Environment

- **CKB version**: ckb 0.112.0-pre (a645ef2 2023-06-20)
- **Chain**: dev
- **Operating system**: Ubuntu 20.04
- **Arch**: x64 
- **Installation**: Built from source

**Comment by eval-exec** [comment]
It seems that: `tx_pool_controller.load_persisted_data` take a long time:
https://github.com/nervosnetwork/ckb/blob/6d00f61b765188679678a56c2eddaa48a5b3ba04/tx-pool/src/service.rs#L621-L624
then `tx_pool_controller.start` will be `false` until `tx_pool_controller.load_persisted_data` finish.

Then, when `ChainService` get a new block, since `tx_pool_controller.start` is `false`, `tx_pool_controller.update_tx_pool_for_reorg` won't be executed, and `template.current.work_id` won't be updated:
https://github.com/nervosnetwork/ckb/blob/6d00f61b765188679678a56c2eddaa48a5b3ba04/tx-pool/src/service.rs#L590-L611

**Comment by eval-exec** [comment]
I'm considering to remove the `tx_pool_controller.service_started()` condition in `ChainService`:
https://github.com/nervosnetwork/ckb/blob/6d00f61b765188679678a56c2eddaa48a5b3ba04/chain/src/chain.rs#L511-L511


@chenyukang @zhangsoledad

**Comment by chenyukang** [comment]
Seems `set_service_started` was not being invoked.
